### ISSUE TITLE
New notes field in merchant api

### ISSUE THREAD

**Issue by montdidier** [sashaskr/pinpayments-go#2]
Just pointing out there is a new notes fields under the director field in the merchants API you can see here in https://pinpayments.com/developers/api-reference/merchants#post-merchants 

https://github.com/sashaskr/pinpayments-go/blob/34084bbda6f894dffb1b0bba3a9d682634dfe079/pinpayments/merchants.go#L17

**Comment by sashaskr** [comment]
@montdidier Thank you Chris!
